version: '3'
services:
  db:
    build:
      ./docker/mysql
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - ./logs:/var/log/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - "./wp/:/var/www/html/"
    links:
      - db
    ports:
      - "80:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   # environment:
  #   #   - PMA_ARBITRARY=1
  #   #   - PMA_HOST=mysql
  #   #   - PMA_USER=root
  #   #   - PMA_PASSWORD=password
  #   links:
  #     - db
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /sessions
