version: '3'
services:
  db:
    build:
      ./docker/mysql
    volumes:
      - "./docker/mysql/data:/var/lib/mysql"
      - ./logs:/var/log/mysql
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    image: wordpress:latest
    volumes:
      - "./wp/:/var/www/html/"
    # restart: always
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_PASSWORD: wordpress

  https-portal:
    image: steveltn/https-portal:1
    ports:
      - "80:80"
      - "443:443"
    # restart: always
    depends_on:
      - wordpress
    environment:
      DOMAINS: 'localhost -> http://wordpress:80'
      STAGE: 'local'
    volumes:
      - ./infra/nginx/conf.d/server.conf.erb:/var/lib/nginx-conf/server.conf.erb:ro
      - ./infra/nginx/conf.d/server.ssl.conf.erb:/var/lib/nginx-conf/server.ssl.conf.erb:ro
      - ./infra/nginx/certs:/var/lib/https-portal
    
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin
  #   # environment:
  #   #   - PMA_ARBITRARY=1
  #   #   - PMA_HOST=mysql
  #   #   - PMA_USER=root
  #   #   - PMA_PASSWORD=password
  #   depends_on:
  #     - db
  #   ports:
  #     - 8080:80
  #   volumes:
  #     - /sessions
